subinclude("//build_defs:e2e")

please_tool(
    name = "please",
    visibility = ["PUBLIC"],
)

filegroup(
    name = "content_checker",
    srcs = ["test_file_content.sh"],
    binary = True,
    visibility = ["PUBLIC"],
)

