subinclude("//build_defs:e2e")

please_tool(
    name = "please",
    visibility = ["PUBLIC"],
)

sh_binary(
    name = "content_checker",
    main = "test_file_content.sh",
    visibility = ["PUBLIC"],
)

